### ISSUE TITLE
Virhekäsittely

### ISSUE THREAD

**Issue by raimohanska** [koodikoulu/koodikoulu.fi#19]
Jos ilmoittautumispäivämäärän syöttää mutten kellonaikaa => formin lähetys hajoaa "palvelinvirheeseen" eikä logeissa näy mitään virheilmoitusta.

**Comment by raimohanska** [comment]
Tässä siis kaksi eri ongelmaa:
1) syötteen käsittely tapauksessa jossa kellonaika puuttuu. Ei saisi tulla "palvelinvirhettä".
2) palvelinvirheen tapauksessa pitäisi nähdä logeista mikä meni vikaan

**Comment by akheron** [comment]
Tässä on traceback:
```
2019-02-15T10:34:53.427582+00:00 app[web.1]: [2019-02-15 12:34:53,426] [31] [ERROR] Internal Server Error: /organize/
2019-02-15T10:34:53.427587+00:00 app[web.1]: Traceback (most recent call last):
2019-02-15T10:34:53.427589+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 223, in get_response
2019-02-15T10:34:53.427593+00:00 app[web.1]: response = middleware_method(request, response)
2019-02-15T10:34:53.427594+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.4/site-packages/django/middleware/clickjacking.py", line 31, in process_response
2019-02-15T10:34:53.427596+00:00 app[web.1]: if response.get('X-Frame-Options', None) is not None:
2019-02-15T10:34:53.427597+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.4/site-packages/django/http/response.py", line 220, in get
2019-02-15T10:34:53.427599+00:00 app[web.1]: return self._headers.get(header.lower(), (None, alternate))[1]
2019-02-15T10:34:53.427600+00:00 app[web.1]: AttributeError: 'str' object has no attribute '_headers'
```
